version: 2

sources:
  - name: raw_data
    tables:
      - name: patients
      - name: patient_gender
      - name: medications
      - name: symptoms
      - name: conditions
      - name: encounters
